### ISSUE TITLE
[BUG] The recent added items showed in the daily notes are not correct

### ISSUE THREAD

**Issue by SChangVic** [alixlahuec/zotero-roam#357]
**zoteroRoam version :** 0.7.18/Latest

**What happened ?**
The recent added items showed in the daily notes are not correct.

I found this issue in recent one week. I don't know if it comes from Zotero or zoteroRoam extension (possibly from the extension given the data in the Dashboard is correct).

You can see from the second screenshot, even though it showed some items they were not corresponding to that added date and time in the Zotero database.

I tried with the previous version of zoteroRoam like v0.7.17 but it kept the same. Very annoying...

**System :**
[ x ] Windows
[ x ] Mac

**Context :**
[ x ] Browser, specify : Chrome
[ x ] Roam desktop app
[ x ] Roam mobile PWA

**Screenshots**
![image](https://github.com/alixlahuec/zotero-roam/assets/68141843/336ee04f-797a-4ffd-b567-f438f541ca6a)
![image](https://github.com/alixlahuec/zotero-roam/assets/68141843/03eab1ed-8cb1-40e5-a799-b7e7909155ec)

**Additional information**
It seemed to happen after I upgraded the Roam and extension in recent one week. It worked without any issues before this upgrade.

**Comment by nowgabis** [comment]
I'm having what seems like the same issue. 
Papers I add to Zotero are not being added (syncing), and papers I added weeks ago are showing up again under today's date.
zoteroRoam version: v0.7.19

**Comment by SChangVic** [comment]
The items it shows are ones added last month. The same issue is also reported in discord by other folk.

**Comment by alixlahuec** [comment]
Hey everyone -- thanks for the report, this was a small regression in the latest release. I fixed this today, and will go out in the next release (pending review by the Roam team).

**Comment by agoodbear** [comment]
thanks~~~~❤️

**Comment by SChangVic** [comment]
Thank you Alix for your dedication to maintaining this plugin which has greatly improved my research workflow.
