### ISSUE TITLE
[BUG] Icon context menu doesn't display correctly

### ISSUE THREAD

**Issue by michaelbbarr** [alixlahuec/zotero-roam#413]
**zoteroRoam version :**
0.7.20

**What happened ?**
A clear and concise description of the problem.
Right-click on green ZoteroRoam extension icon results in screen going dark and I don't see the menu

**To Reproduce**
Activate the ZoteroRoam extension as per usual and try right-clicking on it.

**Expected behavior**
I expect to see the menu, and then to be able to invoke the dashboard

---

**System :**
[X ] Windows
[  ] Mac
[  ] Linux
[  ] Android
[ X] iOS

**Context :**
[ X ] Browser, specify : Chrome - is on the latest version
[ X ] Roam desktop app: both in Windows and on iPad Pro IOS
[  ] Roam mobile PWA

**Screenshots**
If applicable, add screenshots and console logs to explain & help investigate the problem.

**Additional information**

**Comment by SChangVic** [comment]
Same from here.

**Comment by joelchan** [comment]
Same issue!

**Comment by cobblepot1** [comment]
Same issue!

I guess the multiple confirmations show how much people rely on this extension!

**Comment by Navla956** [comment]
Same issues!

Right click doesn't pull up the icon context menu.

**Comment by alixlahuec** [comment]
Hi everyone -- the fix is still pending approval for release to Roam Depot (https://github.com/Roam-Research/roam-depot/pull/782), unfortunately I don't have any insights on when the team will be able to review it.

In the meantime, the Search and the Dashboard are accessible using Roam's command palette -- not the Settings yet, unfortunately, but that'll be added soon.

**Comment by cobblepot1** [comment]
Instructions for manually updating to the fixed version are here: https://discord.com/channels/819277346069938176/819277799356629083/1159743843705573426

**Comment by Navla956** [comment]
> Instructions for manually updating to the fixed version are here: https://discord.com/channels/819277346069938176/819277799356629083/1159743843705573426

Hi thank you! The discord link appears dead to me though. Can you provide a screenshot? (I can also just wait for Roam depot, thank you so much Alixahuec)

**Comment by cobblepot1** [comment]
![image](https://github.com/alixlahuec/zotero-roam/assets/65119937/d14528fd-c6ca-42d0-a9c4-925e598aa83e)
