### ISSUE TITLE
[BUG] Example `customMetadata` function from docs crashes metadata import

### ISSUE THREAD

**Issue by deiwin** [alixlahuec/zotero-roam#99]
**zoteroRoam version :**
v0.7.5 installed from Roam Depot today

**What happened ?** & **To Reproduce**

1. I copied the example `customMetadata` function from [Formatting metadata: JavaScript templates: Getting Started](https://alix-lahuec.gitbook.io/zotero-roam/customization/formatting/javascript-templates#getting-started).
2. I did some modifications which are not relevant to the issue.
3. I tried to import an article but it failed (with no clear feedback in the UI).
4. I looked at the dev console and saw the following issues:
  a. `zoteroRoam.getCreators(item)` had to be changed to `zoteroRoam.getItemCreators(item)`; and
  b. `zoteroRoam.utils.makeDNP(item.data.dateAdded, {brackets: true})` had to be changed to `zoteroRoam.getItemDateAdded(item)`.
  
I would've opened a quick PR for the docs themselves to fix the example, but I couldn't find the source for them.

**Expected behavior**
Copy-pasting the example from docs retains default formatting functionality

---

**System :**
[  ] Windows
[X] Mac
[  ] Linux
[  ] Android
[  ] iOS

**Context :**
[  ] Browser, specify :
[X] Roam desktop app
[  ] Roam mobile PWA

**Comment by alixlahuec** [comment]
Thanks for the flag - I removed it from the docs, so that it only lives in one place (the Observable notebook)!
Will make a ticket for the lack of UI feedback though, the extension should tell you there was a problem 👍
